"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("students", [
      {
        name: "박성준",
        gender: "남",
        grade: "4학년",
        phone_number: "01000000001",
        address: "서울시123 ",
        enrollment_date: new Date(),
        email: "abcd@naver.com",
        status: "재학",
        profile_picture_url: "dafefadfefa",
        parent_phone_number: "01000000002",
        zip_code: "00001",
        admission_type: "정시",
        tuition_status: "입금완료",
        current_semester: "1학기",
        createdAt: new Date(),
        updatedAt: new Date(),
        department_id: 1,
        user_id: 1,
      },
      {
        name: "이석영",
        gender: "남",
        grade: "4학년",
        phone_number: "01000000003",
        address: "서울시1234 ",
        enrollment_date: new Date(),
        email: "abcd1@naver.com",
        status: "졸업",
        profile_picture_url: "dafefadgaefqfefa",
        parent_phone_number: "01000000004",
        zip_code: "00002",
        admission_type: "수시",
        tuition_status: "입금완료",
        current_semester: "2학기",
        createdAt: new Date(),
        updatedAt: new Date(),
        department_id: 1,
        user_id: 2,
      },
      {
        name: "장지웅",
        gender: "남",
        grade: "1학년",
        phone_number: "01000000005",
        address: "서울시12345 ",
        enrollment_date: new Date(),
        email: "abcd12@naver.com",
        status: "휴학",
        profile_picture_url: "dafeqewgadffadfefa",
        parent_phone_number: "01000000005",
        zip_code: "00003",
        admission_type: "수시",
        tuition_status: "입금완료",
        current_semester: "1학기",
        createdAt: new Date(),
        updatedAt: new Date(),
        department_id: 1,
        user_id: 3,
      },
      {
        name: "홍길동",
        gender: "남",
        grade: "4학년",
        phone_number: "01000000006",
        address: "서울시123 ",
        enrollment_date: new Date(),
        email: "abcd123@naver.com",
        status: "재학",
        profile_picture_url: "dafefadfefaqfeaf",
        parent_phone_number: "01000000007",
        zip_code: "00004",
        admission_type: "수시",
        tuition_status: "입금완료",
        current_semester: "1학기",
        createdAt: new Date(),
        updatedAt: new Date(),
        department_id: 1,
        user_id: 4,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    console.log("Students Undoing...");

    return queryInterface.bulkDelete("students", null, {});
  },
};
